### ISSUE TITLE
status always skipped when using galah.atlas_occurences()

### ISSUE THREAD

**Issue by JojoReikun** [AtlasOfLivingAustralia/galah-python#205]
Hey,

I know this python package is still under development and quite new and I find it awesome that you're working on developing a galah python version!!! I am currently working on a python project using ALA data and would love to use this package, instead of having to use an R package to download the data and then python to handle it.

An issue I am currently facing when I try to download data is that it always returns the error message that the json response status is "skipped" and I have tried a lot of options of taxa to search for, filters etc. 

I have configured galah to the Australian Atlas and put in my email that I used for ALA registration. The data_profile is set to "ALA".

The current code I am trying:
`df_counts_project = galah.atlas_occurrences(taxa="Phascolarctos cinereus", use_data_profile=True)`

The errror message:
Traceback (most recent call last):
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\__main__.py", line 11, in <module>
    main()
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\__main__.py", line 7, in main
    download_ala_data()
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\operations\galah_data_download.py", line 48, in download_ala_data
    df_counts_project = galah.atlas_occurrences(taxa="Phascolarctos cinereus", use_data_profile=True)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\galah\atlas_occurrences.py", line 243, in atlas_occurrences
    if response.json()['status'] == "skipped":
KeyError: 'status'

Any feedback on this would be appreciated :)
Thanks!

**Comment by acbuyan** [comment]
Hey Jojo,

Thank you for taking the time to comment!  As the one who's written the lion's share of the package, it's great to hear there are users out there that are excited by this package!

Hm, when I've used it, it gives me ~203,000 occurrence records.  To try and help you, I have a couple of questions and the code I used:

```
>>> galah.galah_config(atlas="Australia", email = "amanda.buyan@csiro.au")
>>> galah.atlas_occurrences(taxa="Phascolarctos cinereus", use_data_profile=True)
```

are you configuring galah like in the above code, or slightly differently?  Is it just `atlas_occurrences()` that isn't working?

**Comment by JojoReikun** [comment]
Hey,

thanks for getting back to me so quickly! Okay, it's good to hear that it works for you! Must be something on my end then!

I have configured as following:
`>>> galah.galah_config(atlas="Australia", email="schjojoultz@gmail.com", data_profile="ALA")
>>> df_counts_project = galah.atlas_occurrences(taxa="Phascolarctos cinereus", use_data_profile=True)`

**Comment by JojoReikun** [comment]
I actually fixed it!

On ALA it says you can log in with an existing google/facebook account to avoid the sign up process. But that doesn't seem to be enough to use that email for the galah_config statement! 

I have resigned up using a different email, and then also received the confirmation link. Using that email now, I can successfully search the occurences!

While I'm at that: What filter word would I have to use to specify a specific database?

**Comment by acbuyan** [comment]
@JojoReikun here's some code 

```
>>> galah.search_all(fields="data")
>>> galah.show_values(field="datasetID")
>>> galah.atlas_counts(filters="datasetID=SU")
```

There is a `datasetName` field; however, you currently can't display the values from that one (I'm currently fixing it and it will be in the next release).

**Comment by JojoReikun** [comment]
THANK YOU!

Yep, I found the datasetName field before, which is what I have tried. 
So thanks for providing a workaround! I will keep testing the code :) You might see me open more issues if I find things I can't work out. 

Thanks so much for working in this! I have to familiarise myself with the code a bit more, but might be able to help you and contribute in future if that's wanted!
