### ISSUE TITLE
Update node_config.csv file

### ISSUE THREAD

**Issue by shahmanash** [AtlasOfLivingAustralia/galah-python#212]
Please update the [node_config.csv](https://github.com/AtlasOfLivingAustralia/galah-python/blob/main/galah/src/galah/node_config.csv) file to include the Swedish namematching service.

```
Sweden,name-matching,names_lookup,https://namematching.biodiversitydata.se/api/getByTaxonID,search_identifiers,TRUE
Sweden,name-matching,names_search_multiple,https://namematching.biodiversitydata.se/api/searchByClassification,search_taxa,TRUE
Sweden,name-matching,names_search_single,https://namematching.biodiversitydata.se/api/search?q={name},search_taxa,TRUE
```
Please note the lucene search index for the service is generated using the GBIF backbone.

**Comment by acbuyan** [comment]
thanks @shahmanash - I'll start working on other atlases this week and next week.  are there other APIs that need to be updated?  If so, could you point me to the correct page?
