### ISSUE TITLE
is API access with JWT tokens working yet?

### ISSUE THREAD

**Issue by JojoReikun** [AtlasOfLivingAustralia/galah-python#217]
Hey acbuyan,

I have been silent for a while as our project got interrupted for a few months, but I am now back at working on automized download of the BioCollect data for a specific project, including all fields available as well as the media (photos of the Koala).

First I generated a list with all field names (n=760) to use these rather than the "basic" setting for downloading atlas occurences of my research UID. 
After receiving error "Expecting value: line 1 column 1 (char0)" a JSON decode error in the request call in atlas_occurrences.py, I added a line to print the raw server response in that python module. 
That showed me that querying all 760 fields produced an URL too long to handle (caused an error 414).
I therefore wrote a loop around this to download the fields in chunks and stitch the data back together. This however then caused a new error (now status: in Queue), error thrown because of line:
`l 311: return pd.read_csv(zipfile.ZipFile(io.BytesIO(zipURL.content)).open('data.csv'),low_memory=False)`
apparently there was a pandas data error "No columns to parse from file".
With this I also received an automatic email from ALA Support that the "Occurrence download failed - data". I did reply to that but haven't heard back yet.

When I read through the ALA API doc, I found that the API I (likely) need to access all data occurrences of that project may be protected?: /occurrences/{recordUuid} (retrieve full record details).
I am unsure if this is the correct API though.
Yet it seems like the JWT token access to protected API is included but not yet functional in galah-python? Judging from the galah_config.py script and the generate_jwt_token.py script?

I have already applied and received a ClientID and Secret and would love to see if this allows me to get the required data of the project...
Yet you have done such incredible work with this package already, that I would rather try and inquire how far JWT tokens are implemented here yet, and if this is the way to solve my access and download issues reaching far beyond the "basic" field list.
I am not a software developer or have experience with APIs, I am more a data analyst. In this case however I can't reach the data I need to analyse, haha, so if there is any way I could try to help with this issue/further development, please let me know.

Hope you can point me in the correct direction, happy to give more specific project details if needed.

Thanks again!
Jojo

**Comment by acbuyan** [comment]
Hi Jojo,

Good to hear from you, and great to hear that you continue to use `galah-python`!  It makes my day :) 

First things first: there have been a couple of updates to `galah-python`; have you updated to the latest version? I don't think this will solve your issue, but I have fixed some bugs along the way and added other options too.

As far as your question on JWT tokens, we’re holding off on JWT token integration until we deploy Cognito. That should be soon but we’re not sure.  In addition, JWT tokens are only for access to sensitive data, and only then to access that you have personally been approved to receive. If these conditions do not apply, then JWT tokens are not what's causing your problem.

Unfortunately, `galah-python` doesn’t support BioCollect APIs, so you can only use galah to get occurrences once they have been passed to biocache.

I may have asked you this before, but what is the reason that you are downloading all fields?  It is unfortunately never a good idea to download all of the ALA fields, as they include spatial data that cannot be relevant to every application. It also includes Darwin Core fields that are rarely populated and may not be useful to you. If you know what data fields you need, you can then include it as an argument to `atlas_occurrences`

**Comment by JojoReikun** [comment]
Hey acbuyan,

Haha, you're welcome! I'm very glad this package exists!
It could very well be that I am looking for the issues in the wrong place 😕 I think JWT tokens were recommended to me by the ALA support mid last year to access BioCollect APIs? Not sure.
But maybe I can work with the galah-python package afterall, the data shouldn't be sensitive. So from what you said it should work! Yes, I have updated the package 🙂

I'll keep playing around and see if I can finally get it downloaded, it shouldn't be this hard haha 😅.
Regarding the field names: I just found that all the field names had such weird names, that I couldn't find the ones I actually need.
I have solved that issue now by downloading the dataset manually once, and extracted the field names from the headings.csv file to use for the download (198 instead of all 760).

I don't know if you remember, but the overall project goal is: I basically want to download new occurrences in this dataset at a frequency xy.
These downloads are then converted to a suitable ESRI format to display it on a map. So the ESRI dashboard we are working on should be kept up-to-date without having to download the ALA KoalaWatch data manually all the time.
The last time I had downloaded the initial data was in July last year, new occurrences since then were 1155, according to the atlas_count function.

I am sorry for the long email below, maybe you can help. I still can't get data downloaded, the results from atlas_occurrences are empty.
No error messages, the console print with the queries are inserted below.
Despite reducing the fields to download to 198, I do not get any data:
When I try to download these 1155 new ones, I end up with an empty data frame. (Console prints are in Consolas font).
query as follows:

df_occurrences_new = galah.atlas_occurrences(filters=filter, verbose=True, fields=fields)

filter = ["taxa==Phascolarctos cinereus", "dataResourceUid==dr19064", "eventDate>=" + str(last_download_date)]

last_download_date:  2023-07-10T14:23:19Z


Below the console print (verbose in atlas_occurrences = True 🙂):

length of list of field names from headings.csv:  198
list of field names from headings.csv:  ['images', 'raw_recordedBy', 'dcterms:modified', 'dcterms:language', 'dcterms:license', 'rightsHolder', 'dcterms:accessRights', 'dcterms:bibliographicCitation', 'references', 'institutionID', 'collectionID', 'datasetID', 'institutionCode', 'collectionCode', 'datasetName', 'ownerInstitutionCode', 'basisOfRecord', 'informationWithheld', 'dataGeneralizations', 'dynamicProperties', 'occurrenceID', 'catalogNumber', 'recordNumber', 'recordedBy', 'individualCount', 'organismQuantity', 'organismQuantityType', 'sex', 'lifeStage', 'reproductiveCondition', 'behavior', 'establishmentMeans', 'occurrenceStatus', 'preparations', 'disposition', 'associatedMedia', 'associatedReferences', 'associatedSequences', 'associatedTaxa', 'otherCatalogNumbers', 'occurrenceRemarks', 'organismID', 'organismName', 'organismScope', 'associatedOccurrences', 'associatedOrganisms', 'previousIdentifications', 'organismRemarks', 'materialSampleID', 'eventID', 'parentEventID', 'fieldNumber', 'eventDate', 'eventTime', 'startDayOfYear', 'endDayOfYear', 'year', 'month', 'day', 'verbatimEventDate', 'habitat', 'samplingProtocol', 'samplingEffort', 'sampleSizeValue', 'sampleSizeUnit', 'fieldNotes', 'eventRemarks', 'locationID', 'higherGeographyID', 'higherGeography', 'continent', 'waterBody', 'islandGroup', 'island', 'country', 'countryCode', 'stateProvince', 'county', 'municipality', 'locality', 'verbatimLocality', 'minimumElevationInMeters', 'maximumElevationInMeters', 'verbatimElevation', 'minimumDepthInMeters', 'maximumDepthInMeters', 'verbatimDepth', 'minimumDistanceAboveSurfaceInMeters', 'maximumDistanceAboveSurfaceInMeters', 'locationAccordingTo', 'locationRemarks', 'decimalLatitude', 'decimalLongitude', 'geodeticDatum', 'coordinateUncertaintyInMeters', 'coordinatePrecision', 'pointRadiusSpatialFit', 'verbatimCoordinates', 'verbatimLatitude', 'verbatimLongitude', 'verbatimCoordinateSystem', 'verbatimSRS', 'footprintWKT', 'footprintSRS', 'footprintSpatialFit', 'georeferencedBy', 'georeferencedDate', 'georeferenceProtocol', 'georeferenceSources', 'georeferenceVerificationStatus', 'georeferenceRemarks', 'geologicalContextID', 'earliestEonOrLowestEonothem', 'latestEonOrHighestEonothem', 'earliestEraOrLowestErathem', 'latestEraOrHighestErathem', 'earliestPeriodOrLowestSystem', 'latestPeriodOrHighestSystem', 'earliestEpochOrLowestSeries', 'latestEpochOrHighestSeries', 'earliestAgeOrLowestStage', 'latestAgeOrHighestStage', 'lowestBiostratigraphicZone', 'highestBiostratigraphicZone', 'lithostratigraphicTerms', 'group', 'formation', 'member', 'bed', 'identificationID', 'identificationQualifier', 'typeStatus', 'identifiedBy', 'dateIdentified', 'identificationReferences', 'identificationVerificationStatus', 'identificationRemarks', 'taxonID', 'scientificNameID', 'acceptedNameUsageID', 'parentNameUsageID', 'originalNameUsageID', 'nameAccordingToID', 'namePublishedInID', 'taxonConceptID', 'raw_scientificName', 'scientificName', 'acceptedNameUsage', 'parentNameUsage', 'originalNameUsage', 'nameAccordingTo', 'namePublishedIn', 'namePublishedInYear', 'higherClassification', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'subgenus', 'specificEpithet', 'infraspecificEpithet', 'taxonRank', 'verbatimTaxonRank', 'scientificNameAuthorship', 'vernacularName', 'nomenclaturalCode', 'taxonomicStatus', 'nomenclaturalStatus', 'taxonRemarks', 'measurementDeterminedDate', 'videos', 'species', 'relationshipAccordingTo', 'resourceRelationshipID', 'measurementRemarks', 'measurementValue', 'relationshipRemarks', 'resourceID', 'relationshipEstablishedDate', 'identifierRole', 'relationshipOfResource', 'measurementMethod', 'identifier', 'provenance', 'sounds', 'recordID', 'rights', 'source', 'measurementID', 'measurementType', 'measurementUnit', 'measurementDeterminedBy', 'measurementAccuracy', 'relatedResourceID', 'images', 'dcterms:type']
downloading RCC data since last download.
last_download_date:  2023-07-10T14:23:19Z
koala_watch_occurrences_count:
totalRecords
0          1155
payload for queryID: {'fq': ['taxa:"Phascolarctos cinereus"', 'dataResourceUid:"dr19064"', 'eventDate:[2023-07-10T14:23:19Z TO *]']}
queryID URL: https://biocache-ws.ala.org.au/ws/webportal/params
method: POST
qid for query: 1709770399220
URL for result:https://biocache-ws.ala.org.au/ws/occurrences/offline/download?email=jojo.schultz%40outlook.de&dwcHeaders=True&reasonTypeId=4&emailNotify=false&fq=%28qid%3A1709770399220%29&fields=images%2Craw_recordedBy%2Cdcterms:modified%2Cdcterms:language%2Cdcterms:license%2CrightsHolder%2Cdcterms:accessRights%2Cdcterms:bibliographicCitation%2Creferences%2CinstitutionID%2CcollectionID%2CdatasetID%2CinstitutionCode%2CcollectionCode%2CdatasetName%2CownerInstitutionCode%2CbasisOfRecord%2CinformationWithheld%2CdataGeneralizations%2CdynamicProperties%2CoccurrenceID%2CcatalogNumber%2CrecordNumber%2CrecordedBy%2CindividualCount%2CorganismQuantity%2CorganismQuantityType%2Csex%2ClifeStage%2CreproductiveCondition%2Cbehavior%2CestablishmentMeans%2CoccurrenceStatus%2Cpreparations%2Cdisposition%2CassociatedMedia%2CassociatedReferences%2CassociatedSequences%2CassociatedTaxa%2CotherCatalogNumbers%2CoccurrenceRemarks%2CorganismID%2CorganismName%2CorganismScope%2CassociatedOccurrences%2CassociatedOrganisms%2CpreviousIdentifications%2CorganismRemarks%2CmaterialSampleID%2CeventID%2CparentEventID%2CfieldNumber%2CeventDate%2CeventTime%2CstartDayOfYear%2CendDayOfYear%2Cyear%2Cmonth%2Cday%2CverbatimEventDate%2Chabitat%2CsamplingProtocol%2CsamplingEffort%2CsampleSizeValue%2CsampleSizeUnit%2CfieldNotes%2CeventRemarks%2ClocationID%2ChigherGeographyID%2ChigherGeography%2Ccontinent%2CwaterBody%2CislandGroup%2Cisland%2Ccountry%2CcountryCode%2CstateProvince%2Ccounty%2Cmunicipality%2Clocality%2CverbatimLocality%2CminimumElevationInMeters%2CmaximumElevationInMeters%2CverbatimElevation%2CminimumDepthInMeters%2CmaximumDepthInMeters%2CverbatimDepth%2CminimumDistanceAboveSurfaceInMeters%2CmaximumDistanceAboveSurfaceInMeters%2ClocationAccordingTo%2ClocationRemarks%2CdecimalLatitude%2CdecimalLongitude%2CgeodeticDatum%2CcoordinateUncertaintyInMeters%2CcoordinatePrecision%2CpointRadiusSpatialFit%2CverbatimCoordinates%2CverbatimLatitude%2CverbatimLongitude%2CverbatimCoordinateSystem%2CverbatimSRS%2CfootprintWKT%2CfootprintSRS%2CfootprintSpatialFit%2CgeoreferencedBy%2CgeoreferencedDate%2CgeoreferenceProtocol%2CgeoreferenceSources%2CgeoreferenceVerificationStatus%2CgeoreferenceRemarks%2CgeologicalContextID%2CearliestEonOrLowestEonothem%2ClatestEonOrHighestEonothem%2CearliestEraOrLowestErathem%2ClatestEraOrHighestErathem%2CearliestPeriodOrLowestSystem%2ClatestPeriodOrHighestSystem%2CearliestEpochOrLowestSeries%2ClatestEpochOrHighestSeries%2CearliestAgeOrLowestStage%2ClatestAgeOrHighestStage%2ClowestBiostratigraphicZone%2ChighestBiostratigraphicZone%2ClithostratigraphicTerms%2Cgroup%2Cformation%2Cmember%2Cbed%2CidentificationID%2CidentificationQualifier%2CtypeStatus%2CidentifiedBy%2CdateIdentified%2CidentificationReferences%2CidentificationVerificationStatus%2CidentificationRemarks%2CtaxonID%2CscientificNameID%2CacceptedNameUsageID%2CparentNameUsageID%2CoriginalNameUsageID%2CnameAccordingToID%2CnamePublishedInID%2CtaxonConceptID%2Craw_scientificName%2CscientificName%2CacceptedNameUsage%2CparentNameUsage%2CoriginalNameUsage%2CnameAccordingTo%2CnamePublishedIn%2CnamePublishedInYear%2ChigherClassification%2Ckingdom%2Cphylum%2Cclass%2Corder%2Cfamily%2Cgenus%2Csubgenus%2CspecificEpithet%2CinfraspecificEpithet%2CtaxonRank%2CverbatimTaxonRank%2CscientificNameAuthorship%2CvernacularName%2CnomenclaturalCode%2CtaxonomicStatus%2CnomenclaturalStatus%2CtaxonRemarks%2CmeasurementDeterminedDate%2Cvideos%2Cspecies%2CrelationshipAccordingTo%2CresourceRelationshipID%2CmeasurementRemarks%2CmeasurementValue%2CrelationshipRemarks%2CresourceID%2CrelationshipEstablishedDate%2CidentifierRole%2CrelationshipOfResource%2CmeasurementMethod%2Cidentifier%2Cprovenance%2Csounds%2CrecordID%2Crights%2Csource%2CmeasurementID%2CmeasurementType%2CmeasurementUnit%2CmeasurementDeterminedBy%2CmeasurementAccuracy%2CrelatedResourceID%2Cimages%2Cdcterms:type%2C&qa=none&flimit=-1
method: GET
Data for download:
https://biocache.ala.org.au/biocache-download/7d58aab5-1e0f-384d-ba9a-f632fb210b51/1709770399748/data.zip
size of dataframe (new data entries):  0

I also tried to download all data again (totalRecords n=2696), without passing an eventDate in the filter, but again the size of the dataFrame for occurrences is (0, 198):
Query for that case:

There is no last download date given, initial_download should be true, correct? (y/n): >? y
initial_download:  True
Number of occurrences for the Redlands Coast Koala Watch project:    totalRecords
0          2696
Do you want to download all data? (y/n): >? y
payload for queryID: {'fq': ['taxa:"Phascolarctos cinereus"', 'dataResourceUid:"dr19064"']}
queryID URL: https://biocache-ws.ala.org.au/ws/webportal/params
method: POST
qid for query: 1709774967146
URL for result:https://biocache-ws.ala.org.au/ws/occurrences/offline/download?email=jojo.schultz%40outlook.de&dwcHeaders=True&reasonTypeId=4&emailNotify=false&fq=%28qid%3A1709774967146%29&fields=images%2Craw_recordedBy%2Cdcterms:modified%2Cdcterms:language%2Cdcterms:license%2CrightsHolder%2Cdcterms:accessRights%2Cdcterms:bibliographicCitation%2Creferences%2CinstitutionID%2CcollectionID%2CdatasetID%2CinstitutionCode%2CcollectionCode%2CdatasetName%2CownerInstitutionCode%2CbasisOfRecord%2CinformationWithheld%2CdataGeneralizations%2CdynamicProperties%2CoccurrenceID%2CcatalogNumber%2CrecordNumber%2CrecordedBy%2CindividualCount%2CorganismQuantity%2CorganismQuantityType%2Csex%2ClifeStage%2CreproductiveCondition%2Cbehavior%2CestablishmentMeans%2CoccurrenceStatus%2Cpreparations%2Cdisposition%2CassociatedMedia%2CassociatedReferences%2CassociatedSequences%2CassociatedTaxa%2CotherCatalogNumbers%2CoccurrenceRemarks%2CorganismID%2CorganismName%2CorganismScope%2CassociatedOccurrences%2CassociatedOrganisms%2CpreviousIdentifications%2CorganismRemarks%2CmaterialSampleID%2CeventID%2CparentEventID%2CfieldNumber%2CeventDate%2CeventTime%2CstartDayOfYear%2CendDayOfYear%2Cyear%2Cmonth%2Cday%2CverbatimEventDate%2Chabitat%2CsamplingProtocol%2CsamplingEffort%2CsampleSizeValue%2CsampleSizeUnit%2CfieldNotes%2CeventRemarks%2ClocationID%2ChigherGeographyID%2ChigherGeography%2Ccontinent%2CwaterBody%2CislandGroup%2Cisland%2Ccountry%2CcountryCode%2CstateProvince%2Ccounty%2Cmunicipality%2Clocality%2CverbatimLocality%2CminimumElevationInMeters%2CmaximumElevationInMeters%2CverbatimElevation%2CminimumDepthInMeters%2CmaximumDepthInMeters%2CverbatimDepth%2CminimumDistanceAboveSurfaceInMeters%2CmaximumDistanceAboveSurfaceInMeters%2ClocationAccordingTo%2ClocationRemarks%2CdecimalLatitude%2CdecimalLongitude%2CgeodeticDatum%2CcoordinateUncertaintyInMeters%2CcoordinatePrecision%2CpointRadiusSpatialFit%2CverbatimCoordinates%2CverbatimLatitude%2CverbatimLongitude%2CverbatimCoordinateSystem%2CverbatimSRS%2CfootprintWKT%2CfootprintSRS%2CfootprintSpatialFit%2CgeoreferencedBy%2CgeoreferencedDate%2CgeoreferenceProtocol%2CgeoreferenceSources%2CgeoreferenceVerificationStatus%2CgeoreferenceRemarks%2CgeologicalContextID%2CearliestEonOrLowestEonothem%2ClatestEonOrHighestEonothem%2CearliestEraOrLowestErathem%2ClatestEraOrHighestErathem%2CearliestPeriodOrLowestSystem%2ClatestPeriodOrHighestSystem%2CearliestEpochOrLowestSeries%2ClatestEpochOrHighestSeries%2CearliestAgeOrLowestStage%2ClatestAgeOrHighestStage%2ClowestBiostratigraphicZone%2ChighestBiostratigraphicZone%2ClithostratigraphicTerms%2Cgroup%2Cformation%2Cmember%2Cbed%2CidentificationID%2CidentificationQualifier%2CtypeStatus%2CidentifiedBy%2CdateIdentified%2CidentificationReferences%2CidentificationVerificationStatus%2CidentificationRemarks%2CtaxonID%2CscientificNameID%2CacceptedNameUsageID%2CparentNameUsageID%2CoriginalNameUsageID%2CnameAccordingToID%2CnamePublishedInID%2CtaxonConceptID%2Craw_scientificName%2CscientificName%2CacceptedNameUsage%2CparentNameUsage%2CoriginalNameUsage%2CnameAccordingTo%2CnamePublishedIn%2CnamePublishedInYear%2ChigherClassification%2Ckingdom%2Cphylum%2Cclass%2Corder%2Cfamily%2Cgenus%2Csubgenus%2CspecificEpithet%2CinfraspecificEpithet%2CtaxonRank%2CverbatimTaxonRank%2CscientificNameAuthorship%2CvernacularName%2CnomenclaturalCode%2CtaxonomicStatus%2CnomenclaturalStatus%2CtaxonRemarks%2CmeasurementDeterminedDate%2Cvideos%2Cspecies%2CrelationshipAccordingTo%2CresourceRelationshipID%2CmeasurementRemarks%2CmeasurementValue%2CrelationshipRemarks%2CresourceID%2CrelationshipEstablishedDate%2CidentifierRole%2CrelationshipOfResource%2CmeasurementMethod%2Cidentifier%2Cprovenance%2Csounds%2CrecordID%2Crights%2Csource%2CmeasurementID%2CmeasurementType%2CmeasurementUnit%2CmeasurementDeterminedBy%2CmeasurementAccuracy%2CrelatedResourceID%2Cimages%2Cdcterms:type%2C&qa=none&flimit=-1
method: GET
Data for download:
https://biocache.ala.org.au/biocache-download/7d58aab5-1e0f-384d-ba9a-f632fb210b51/1709774967617/data.zip
size of dataframe:  (0, 198)
payload for queryID: {'fq': ['taxa:"Phascolarctos cinereus"', 'dataResourceUid:"dr19064"']}
queryID URL: https://biocache-ws.ala.org.au/ws/webportal/params
method: POST
qid for query: 1709774968402
URL for result:https://biocache-ws.ala.org.au/ws/occurrences/offline/download?email=jojo.schultz%40outlook.de&dwcHeaders=True&reasonTypeId=4&emailNotify=false&fq=%28qid%3A1709774968402%29&fields=decimalLatitude%2CdecimalLongitude%2CeventDate%2CscientificName%2CtaxonConceptID%2CrecordID%2CdataResourceName%2CoccurrenceStatus%2Cmultimedia%2CmultimediaLicence%2Cimages%2Cvideos%2Csounds%2C&qa=none&flimit=-1
method: GET
Data for download:
https://biocache.ala.org.au/biocache-download/7d58aab5-1e0f-384d-ba9a-f632fb210b51/1709774968804/data.zip
size of media dataframe:  (3806, 17)

Yet the media dataframe size (collect=False) is (3806, 17). Saving this to a csv file works and the images are donwloaded as well if I put collect = True (even though the file can't be opened as format seems to unsupported for some reason.)


Do you have any idea why the dataframe remains empty?

Thanks so much for your consistent support!

Cheers,
Jojo

________________________________

**Comment by acbuyan** [comment]
Hi again Jojo,

I get what you mean about the headings.  If you're not overly familiar with the concept of Darwin Core (https://dwc.tdwg.org/) headings, it can feel overwhelming.

Out of curiosity, have you tried the `search_all` function in `galah`? It could help you narrow down your fields search?  You can use `show_all` to show all the terms, and `search_all` to find terms with keywords either in the term (id) itself or the description.  It looks like this:

```
                    id                                     description   type link
0        _nest_parent_                                             NaN  field  NaN
1          _nest_path_                                             NaN  field  NaN
2               _root_                                             NaN  field  NaN
3       abcdTypeStatus                   ABCD field in use by herbaria  field  NaN
4    acceptedNameUsage  http://rs.tdwg.org/dwc/terms/acceptedNameUsage  field  NaN
..                 ...                                             ...    ...  ...
755  multimediaLicence                              Media filter field  media     
756             images                              Media filter field  media     
757             videos                              Media filter field  media     
758             sounds                              Media filter field  media     
759                qid                Reference to pre-generated query  other     

[760 rows x 4 columns]
>>> galah.search_all(fields="latitude")
                    id                                        description   type                                               link
0      decimalLatitude  The decimal latitude associated with this reco...  field  https://github.com/AtlasOfLivingAustralia/ala-...
1     verbatimLatitude      http://rs.tdwg.org/dwc/terms/verbatimLatitude  field                                                NaN
2  raw_decimalLatitude  The decimal latitude as supplied by the data p...  field                                                NaN
```

As far as getting the data, I don't think it was a problem with what you were doing, I think it was with how `galah-python` was constructing the URLs.  I've patched it and pushed my changes to the Python Package Index, so all you should need to do is update your installation and it should work.

**Comment by JojoReikun** [comment]
Hey,

thanks! Yeah I have tried the search_all, but it's still hard to pick all the fields that I will need, as there are quite a few...

I have upgraded galah-python, but the dataframe is still empty... ?

payload for queryID: {'fq': ['taxa:"Phascolarctos cinereus"', 'dataResourceUid:"dr19064"']}
queryID URL: https://biocache-ws.ala.org.au/ws/webportal/params
method: POST
qid for query: 1709852490562
URL for result:https://biocache-ws.ala.org.au/ws/occurrences/offline/download?email=jojo.schultz%40outlook.de&dwcHeaders=True&reasonTypeId=4&emailNotify=false&fq=%28qid%3A1709852490562%29&fields=images%2Craw_recordedBy%2Cdcterms:modified%2Cdcterms:language%2Cdcterms:license%2CrightsHolder%2Cdcterms:accessRights%2Cdcterms:bibliographicCitation%2Creferences%2CinstitutionID%2CcollectionID%2CdatasetID%2CinstitutionCode%2CcollectionCode%2CdatasetName%2CownerInstitutionCode%2CbasisOfRecord%2CinformationWithheld%2CdataGeneralizations%2CdynamicProperties%2CoccurrenceID%2CcatalogNumber%2CrecordNumber%2CrecordedBy%2CindividualCount%2CorganismQuantity%2CorganismQuantityType%2Csex%2ClifeStage%2CreproductiveCondition%2Cbehavior%2CestablishmentMeans%2CoccurrenceStatus%2Cpreparations%2Cdisposition%2CassociatedMedia%2CassociatedReferences%2CassociatedSequences%2CassociatedTaxa%2CotherCatalogNumbers%2CoccurrenceRemarks%2CorganismID%2CorganismName%2CorganismScope%2CassociatedOccurrences%2CassociatedOrganisms%2CpreviousIdentifications%2CorganismRemarks%2CmaterialSampleID%2CeventID%2CparentEventID%2CfieldNumber%2CeventDate%2CeventTime%2CstartDayOfYear%2CendDayOfYear%2Cyear%2Cmonth%2Cday%2CverbatimEventDate%2Chabitat%2CsamplingProtocol%2CsamplingEffort%2CsampleSizeValue%2CsampleSizeUnit%2CfieldNotes%2CeventRemarks%2ClocationID%2ChigherGeographyID%2ChigherGeography%2Ccontinent%2CwaterBody%2CislandGroup%2Cisland%2Ccountry%2CcountryCode%2CstateProvince%2Ccounty%2Cmunicipality%2Clocality%2CverbatimLocality%2CminimumElevationInMeters%2CmaximumElevationInMeters%2CverbatimElevation%2CminimumDepthInMeters%2CmaximumDepthInMeters%2CverbatimDepth%2CminimumDistanceAboveSurfaceInMeters%2CmaximumDistanceAboveSurfaceInMeters%2ClocationAccordingTo%2ClocationRemarks%2CdecimalLatitude%2CdecimalLongitude%2CgeodeticDatum%2CcoordinateUncertaintyInMeters%2CcoordinatePrecision%2CpointRadiusSpatialFit%2CverbatimCoordinates%2CverbatimLatitude%2CverbatimLongitude%2CverbatimCoordinateSystem%2CverbatimSRS%2CfootprintWKT%2CfootprintSRS%2CfootprintSpatialFit%2CgeoreferencedBy%2CgeoreferencedDate%2CgeoreferenceProtocol%2CgeoreferenceSources%2CgeoreferenceVerificationStatus%2CgeoreferenceRemarks%2CgeologicalContextID%2CearliestEonOrLowestEonothem%2ClatestEonOrHighestEonothem%2CearliestEraOrLowestErathem%2ClatestEraOrHighestErathem%2CearliestPeriodOrLowestSystem%2ClatestPeriodOrHighestSystem%2CearliestEpochOrLowestSeries%2ClatestEpochOrHighestSeries%2CearliestAgeOrLowestStage%2ClatestAgeOrHighestStage%2ClowestBiostratigraphicZone%2ChighestBiostratigraphicZone%2ClithostratigraphicTerms%2Cgroup%2Cformation%2Cmember%2Cbed%2CidentificationID%2CidentificationQualifier%2CtypeStatus%2CidentifiedBy%2CdateIdentified%2CidentificationReferences%2CidentificationVerificationStatus%2CidentificationRemarks%2CtaxonID%2CscientificNameID%2CacceptedNameUsageID%2CparentNameUsageID%2CoriginalNameUsageID%2CnameAccordingToID%2CnamePublishedInID%2CtaxonConceptID%2Craw_scientificName%2CscientificName%2CacceptedNameUsage%2CparentNameUsage%2CoriginalNameUsage%2CnameAccordingTo%2CnamePublishedIn%2CnamePublishedInYear%2ChigherClassification%2Ckingdom%2Cphylum%2Cclass%2Corder%2Cfamily%2Cgenus%2Csubgenus%2CspecificEpithet%2CinfraspecificEpithet%2CtaxonRank%2CverbatimTaxonRank%2CscientificNameAuthorship%2CvernacularName%2CnomenclaturalCode%2CtaxonomicStatus%2CnomenclaturalStatus%2CtaxonRemarks%2CmeasurementDeterminedDate%2Cvideos%2Cspecies%2CrelationshipAccordingTo%2CresourceRelationshipID%2CmeasurementRemarks%2CmeasurementValue%2CrelationshipRemarks%2CresourceID%2CrelationshipEstablishedDate%2CidentifierRole%2CrelationshipOfResource%2CmeasurementMethod%2Cidentifier%2Cprovenance%2Csounds%2CrecordID%2Crights%2Csource%2CmeasurementID%2CmeasurementType%2CmeasurementUnit%2CmeasurementDeterminedBy%2CmeasurementAccuracy%2CrelatedResourceID%2Cimages%2Cdcterms:type&qa=none&flimit=-1
method: GET
Data for download:
https://biocache.ala.org.au/biocache-download/7d58aab5-1e0f-384d-ba9a-f632fb210b51/1709852491183/data.zip
size of occurrences dataframe:  (0, 198)

Is there still something wrong with the URL?
Thanks for such prompt help 🙂

Jojo
________________________________

**Comment by acbuyan** [comment]
yes - do you mind double-checking what version of `galah-python` you have?  It should be `0.8.3`.  If it is that version and it is still not working, then I'll have to go back to the drawing board.

**Comment by JojoReikun** [comment]
Yup it's 0.8.3!
Yesterday's was 0.8.2...
Sorry!

I will reduce the number fo fields a bit more too.
Let me know if I can help with debugging!
________________________________

**Comment by acbuyan** [comment]
Ok, this might sound weird, but ... try putting `decimalLatitude` at the beginning of your list of terms and see if that works

**Comment by JojoReikun** [comment]
That works!
Interesting fix :)

What did that change?

**Comment by acbuyan** [comment]
I don't know - I'll ask the systems team and see why.

**Comment by JojoReikun** [comment]
Thank you!

**Comment by acbuyan** [comment]
Hi Jojo,
Wanted to let you know that it is on the ALA side of things.  I'm not sure when a fix is coming, so for now keep using the `decimalLatitude` fix.  I'm going to close the issue for now, but do let me know if anything else comes up!
