### ISSUE TITLE
atlas_media() collect = True returning broken images

### ISSUE THREAD

**Issue by slopezmarcano** [AtlasOfLivingAustralia/galah-python#218]
Hi, I have been using the atlas_media to download images from ALA and the images being downloaded seem to be broken. Can you please advise if its a bug or if I am doing something wrong? 

Here are my steps

`import galah`
`galah.galah_config(atlas="Australia")`
`galah.galah_config(email="")`
`galah.atlas_media(taxa="Tiliqua nigrolutea", filters= "year=2023", multimedia="images", collect=True, path='/media')`

Files get downloaded in jpeg formats, but the files are all broken and only 3KB in size.

I have tried the same functionality in the R package, and in there is working ok.

**Comment by acbuyan** [comment]
HI @slopezmarcano , thank you for letting us know about this issue!  I just have a couple of questions for me:

- what version of `galah-python` do you have installed?
- do you have an email that is registered with the ALA? Or are you able to download the images without an email?
- the R version does this command as expected? (confirming this)

**Comment by acbuyan** [comment]
also @slopezmarcano , could you give me example R code?

**Comment by slopezmarcano** [comment]
> HI @slopezmarcano , thank you for letting us know about this issue! I just have a couple of questions for me:
> 
> * what version of `galah-python` do you have installed?
> * do you have an email that is registered with the ALA? Or are you able to download the images without an email?
> * the R version does this command as expected? (confirming this)

1) galah-python==0.9.1
2) Yes I do, my QCIF email (s.lopezmarcano@qcif.edu.au). I did not try to download the images without an email
3) Yes it does

**Comment by slopezmarcano** [comment]
> also @slopezmarcano , could you give me example R code?
```
`
# Objective: Download images of Tachyglossus aculeatus from 2024
#Author: Dr Sebastian Lopez Marcano (QCIF/WildObs)
#Date: 2024-10-18

#Setup renv
`library(renv)`

# # Activate renv
`renv::activate()`

# # Install galah package
install.packages("galah")

# # Snapshot renv
renv::snapshot()

# Load libraries
library(galah)

# Config galah with region and email + define directory
galah_config(atlas = "Australia", email = "s.lopezmarcano@qcif.edu.au", directory="media")

# Download images of Tachyglossus aculeatus from 2024
galah_call() |> 
galah_identify("Tachyglossus aculeatus") |> 
galah_filter(year == 2024, cl22 == "Queensland") |> 
atlas_media() |> 
collect_media(thumbnail = FALSE) # thumbnail = FALSE to download full resolution images
```

**Comment by acbuyan** [comment]
Hi Sebastian,
Apologies for the delayed response - I've been working on fixing this bug, which, indeed it was.
I've fixed the atlas_media() function so it downloads images properly, and have added the ability to download thumbnails vs. original images, and a progress bar (which can be turned off).  Thanks for bringing this bug to my attention!  If you find any more bugs, please do not hesitate to post on here.
